### ISSUE TITLE
merge_method is fake option

### ISSUE THREAD

**Issue by bluelovers** [tgymnich/fork-sync#176]
current code didn't has any work with `merge_method`

**Comment by tgymnich** [comment]
Good catch. This was lost when switching to node 20. [90fff02](https://github.com/tgymnich/fork-sync/commit/90fff029bc50e607d55ebcffa282ff6329adb8b1) should fix this

**Comment by bluelovers** [comment]
> Good catch. This was lost when switching to node 20. [90fff02](https://github.com/tgymnich/fork-sync/commit/90fff029bc50e607d55ebcffa282ff6329adb8b1) should fix this.

how can i fix this issue?

![image](https://github.com/tgymnich/fork-sync/assets/167966/b62ccc34-7aee-4f1d-8f3b-22261d4b29fc)

**Comment by tgymnich** [comment]
Looks like you swapped base and head.
