### ISSUE TITLE
Failure Does Not Fail The Build

### ISSUE THREAD

**Issue by anton-yurchenko** [tgymnich/fork-sync#22]
Hey,
The misconfigured workflow will mark the build passed despite the step being failed. *([example](https://github.com/anton-yurchenko/project-layout/runs/1180618493?check_suite_focus=true))*:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/33016810/94526888-de8de080-023e-11eb-8470-9273175356b7.png">

Maybe we can catch that and `core.setFailed(`<error-msg>`)` && `process.exit(1)`? 🤔

**Comment by tgymnich** [comment]
Well this is not exactly a failure. The API just throws an error when we want to create a PR with no changes. The logging is there to debug another issue (#20) and I should probably reword the message or remove it.

**Comment by anton-yurchenko** [comment]
Alright! Thanks!
