### ISSUE TITLE
Are arguments supported?

### ISSUE THREAD

**Issue by qiangxinglin** [tgymnich/fork-sync#25]
Hi,

In my project, I would prefer that the conflicts always use my version, which means 'merge -Xours' would be really helpful.
Is there any way to implement this?

**Comment by tgymnich** [comment]
fork-sync uses [octokit rest](https://octokit.github.io/rest.js/v18#pulls-merge), which unfortunately does not support `ours`. There are GitHub Actions based on the `git` cl that might be able to do what you need.
